web/router.ex
defmodule Bep.Router do
  use Bep.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Bep.Auth, repo: Bep.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/super-admin", Bep, as: :sa do
    pipe_through [:browser, :authenticate_super_admin]

    resources "/", SuperAdminController, only: [
      :index, :new, :create, :edit, :update
    ]
    get "/new-client-admin", SuperAdminController, :new_client_admin
    post "/create-client-admin", SuperAdminController, :create_client_admin
    get "/edit-client-admin", SuperAdminController, :edit_client_admin
    put "/update-client-admin/:id", SuperAdminController, :update_client_admin
    get "/list-users", MessagesController, :list_users
    post "/list-users", MessagesController, :view_user_messages
    get "/messages", MessagesController, :view_messages
    get "/message_sent", MessagesController, :message_sent
    resources "/messages", MessagesController, only: [:create, :new]
  end

  scope "/", Bep, as: :ca do
    pipe_through [:browser, :authenticate_ca]
    get "/list-users", MessagesController, :list_users
    post "/list-users", MessagesController, :view_user_messages
    get "/message_sent", MessagesController, :message_sent
    resources "/messages", MessagesController, only: [:create, :new]
  end

  scope "/", Bep do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create]
    resources "/consent", ConsentController, only: [:index]
    resources "/about", AboutController, only: [:index]
    resources "/password", PasswordController, only: [:index]
    post "/password/request", PasswordController, :request
    get "/password/reset", PasswordController, :reset
    post "/password/reset", PasswordController, :reset
  end

  scope "/", Bep do
    pipe_through [:browser, :authenticate_user]

    get "/paper-details", BearController, :paper_details
    get "/check-validity", BearController, :check_validity
    get "/calculate-results", BearController, :calculate_results
    get "/relevance", BearController, :relevance
    get "/bear-complete", BearController, :complete
    get "/create-pdf", BearController, :create_pdf
    post "/download-pdf", BearController, :download_pdf
    resources "/bears", BearController, only: [:index]
    resources "/bear-form", BearController, only: [:create]
    resources "/pico", PicoSearchController, [:new, :create, :edit]
    resources "/history", HistoryController, only: [:index]
    resources "/search", SearchController, only: [:index, :create]
    post "/search/category", SearchController, :filter
    resources "/settings", SettingsController, only: [:index]
    get "/password/change", PasswordController, :change_password
    post "/password/change", PasswordController, :change_password
    get "/messages", MessagesController, :view_messages
  end

  scope "/note", Bep do
    pipe_through [:browser, :authenticate_user]
    resources "/search", NoteSearchController
  end

  # Other scopes may use custom stacks.
  scope "/", Bep do
    pipe_through :api
    resources "/publication", PublicationController, only: [:create]
    get "/load", SearchController, :load
  end

  scope "/:client_slug", Bep, as: :client_slug do
    pipe_through [:browser, :authenticate_client]

    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create]
    resources "/consent", ConsentController, only: [:index]
    resources "/about", AboutController, only: [:index]
    resources "/password", PasswordController, only: [:index]
    post "/password/request", PasswordController, :request
    get "/password/reset", PasswordController, :reset
    post "/password/reset", PasswordController, :reset
  end
end

web/controllers/session_controller.ex
defmodule Bep.SessionController do
  use Bep.Web, :controller
  alias Bep.Auth

  def new(conn, _) do
    if conn.assigns.current_user do
      redirect(conn, to: search_path(conn, :index))
    else
      bg_colour = get_client_colour(conn, :login_page_bg_colour)
      btn_colour = get_client_colour(conn, :btn_colour)
      render(
        conn,
        "new.html",
        bg_colour: bg_colour,
        btn_colour: btn_colour
      )
    end
  end

  def create(conn, %{"session" => %{"email" => email, "password" => pass}}) do
    case Auth.login_by_email_and_pass(conn, email, pass, repo: Repo) do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: search_path(conn, :index))
      {:error, _reason, conn} ->
        bg_colour = get_client_colour(conn, :login_page_bg_colour)
        btn_colour = get_client_colour(conn, :btn_colour)

        conn
        |> put_flash(:error, "Invalid email/password combination")
        |> render(
          "new.html",
          bg_colour: bg_colour,
          btn_colour: btn_colour
        )
    end
  end
end

web/views/session_view.ex
defmodule Bep.SessionView do
  use Bep.Web, :view
end

web/templates/session/new.html.eex
<section style="background-color:<%= @bg_colour %>" class="tc white pt4 pb3">
  <h1 class="f3 fw1 lh-copy pt3 mv0">Welcome Back.</h1>
  <h2 class="f5 fw1 lh-copy mv0">Please Log In</h2>
</section>
<section class="pa3 w-80 w-30-ns center">
  <p class="f5 tc">If you are on a public computer, remember to log out.</p>
  <%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
    <p class="alert alert-danger ma0" role="alert"><%= get_flash(@conn, :error) %></p>
    <label for="user_email" class="db mt4">Email Address *</label>
    <%= text_input f, :email, placeholder: "example@email.com", class: "mv2 pa2 w-100 ba br2 b--black-20" %>
    <%= error_tag f, :email %>
    <label for="user_password" class="db mh0-ns mt3">Password *</label>
    <%= password_input f , :password, placeholder: "Password", class: "mv2 pa2 w-100 ba br2 b--black-20 db" %>
    <%= error_tag f,:password %>
    <%= if @client.slug == "default" do %>
      <img src="../images/gray-info.svg" alt="info" class="v-mid">
    <% else %>
      <img src="../../images/gray-info.svg" alt="info" class="v-mid">
    <% end %>
    <p class="pl1 bep-gray dib">Min 6 characters</p>
    <div class="tc pt3">
      <%= submit "Start Searching", [class: "white ph4 pv3 ba br2 link db mb4 center pointer", style: "background-color:#{@btn_colour}"] %>
      <%= slug_link_helper(@conn, "Register a New Account", &client_slug_consent_path/3, &consent_path/2, [route: :index, class: "bep-gray db mb2"]) %>
      <%= slug_link_helper(@conn, "Forgotten your Password?", &client_slug_password_path/3, &password_path/2, [route: :index, class: "bep-gray db"]) %>
    </div>
  <% end %>
</section>