web/router.ex
defmodule Bep.Router do
  use Bep.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Bep.Auth, repo: Bep.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/super-admin", Bep, as: :sa do
    pipe_through [:browser, :authenticate_super_admin]

    resources "/", SuperAdminController, only: [
      :index, :new, :create, :edit, :update
    ]
    get "/new-client-admin", SuperAdminController, :new_client_admin
    post "/create-client-admin", SuperAdminController, :create_client_admin
    get "/edit-client-admin", SuperAdminController, :edit_client_admin
    put "/update-client-admin/:id", SuperAdminController, :update_client_admin
    get "/list-users", MessagesController, :list_users
    post "/list-users", MessagesController, :view_user_messages
    get "/messages", MessagesController, :view_messages
    get "/message_sent", MessagesController, :message_sent
    resources "/messages", MessagesController, only: [:create, :new]
  end

  scope "/", Bep, as: :ca do
    pipe_through [:browser, :authenticate_ca]
    get "/list-users", MessagesController, :list_users
    post "/list-users", MessagesController, :view_user_messages
    get "/message_sent", MessagesController, :message_sent
    resources "/messages", MessagesController, only: [:create, :new]
  end

  scope "/", Bep do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create]
    resources "/consent", ConsentController, only: [:index]
    resources "/about", AboutController, only: [:index]
    resources "/password", PasswordController, only: [:index]
    post "/password/request", PasswordController, :request
    get "/password/reset", PasswordController, :reset
    post "/password/reset", PasswordController, :reset
  end

  scope "/", Bep do
    pipe_through [:browser, :authenticate_user]

    get "/paper-details", BearController, :paper_details
    get "/check-validity", BearController, :check_validity
    get "/calculate-results", BearController, :calculate_results
    get "/relevance", BearController, :relevance
    get "/bear-complete", BearController, :complete
    get "/create-pdf", BearController, :create_pdf
    post "/download-pdf", BearController, :download_pdf
    resources "/bears", BearController, only: [:index]
    resources "/bear-form", BearController, only: [:create]
    resources "/pico", PicoSearchController, [:new, :create, :edit]
    resources "/history", HistoryController, only: [:index]
    resources "/search", SearchController, only: [:index, :create]
    post "/search/category", SearchController, :filter
    resources "/settings", SettingsController, only: [:index]
    get "/password/change", PasswordController, :change_password
    post "/password/change", PasswordController, :change_password
    get "/messages", MessagesController, :view_messages
  end

  scope "/note", Bep do
    pipe_through [:browser, :authenticate_user]
    resources "/search", NoteSearchController
  end

  # Other scopes may use custom stacks.
  scope "/", Bep do
    pipe_through :api
    resources "/publication", PublicationController, only: [:create]
    get "/load", SearchController, :load
  end

  scope "/:client_slug", Bep, as: :client_slug do
    pipe_through [:browser, :authenticate_client]

    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create]
    resources "/consent", ConsentController, only: [:index]
    resources "/about", AboutController, only: [:index]
    resources "/password", PasswordController, only: [:index]
    post "/password/request", PasswordController, :request
    get "/password/reset", PasswordController, :reset
    post "/password/reset", PasswordController, :reset
  end
end

web/models/pico_search.ex
defmodule Bep.PicoSearch do
  @moduledoc """
  PicoSearch model
  """
  use Bep.Web, :model
  alias Bep.{BearAnswers, NoteSearch, PicoOutcome, PicoSearch, Repo}

  schema "pico_searches" do
    belongs_to :note_search, NoteSearch
    field :p, :string
    field :i, :string
    field :c, :string
    field :position, :string
    field :probability, :integer
    has_many :pico_outcome, PicoOutcome
    has_many :bear_answers, BearAnswers
    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    params_list = [:p, :i, :c, :position, :probability]

    struct
    |> cast(params, params_list)
  end

  # HELPERS
  def get_pico_search(search) do
    if search.uncertainty do
      query =
        from ps in PicoSearch,
        join: ns in NoteSearch, on: ps.note_search_id == ns.id,
        where: ns.search_id == ^search.id,
        preload: [:note_search, note_search: :search],
        order_by: [desc: ps.id],
        limit: 1

      Repo.one(query)
    else
      nil
    end
  end

  def get_related_pico_outcomes(ps_id, to_index) do
    1..to_index
    |> Enum.map(&get_pico_outcome(ps_id, &1))
    |> Enum.reject(&(&1 == nil))
  end

  defp get_pico_outcome(ps_id, index) do
    query =
      from po in PicoOutcome,
      where: po.pico_search_id == ^ps_id and po.o_index == ^index,
      order_by: [desc: po.id],
      limit: 1

    Repo.one(query)
  end
end

web/controllers/pico_search_controller.ex
defmodule Bep.PicoSearchController do
  use Bep.Web, :controller
  alias Bep.{NoteSearch, PicoSearch, PicoOutcome, Search}
  alias Ecto.Changeset

  def new(conn, %{"note_id" => note_id, "search_id" => search_id}) do
    search = Repo.get(Search, search_id)
    note_search = Repo.get_by(NoteSearch, search_id: search_id)
    changeset = PicoSearch.changeset(%PicoSearch{})

    assigns = [
      changeset: changeset,
      note_id: note_id,
      search: search,
      outcomes: [],
      note_search: note_search
    ]

    render(conn, "new.html", assigns)
  end

  def create(conn, %{"pico_search" => pico_search_params} = params) do
    pico_search_params = update_prob(pico_search_params)
    search_id = pico_search_params["search_id"]
    search = Repo.get(Search, search_id)

    pico_outcomes = get_pico_outcomes(pico_search_params)
    pico_search = insert_or_update_pico(pico_search_params)

    Enum.each(pico_outcomes, fn(outcome) ->
      %PicoOutcome{}
      |> PicoOutcome.changeset(outcome)
      |> Changeset.put_assoc(:pico_search, pico_search)
      |> Repo.insert!()
    end)

    case Map.get(params, "search_trip") do
      nil -> # Save and continue later route
        redirect(conn, to: search_path(conn, :index))
      "true" -> # search api with pico search (regular search for now)
        user = conn.assigns.current_user
        search_data =
          %{"term" => search.term}
          |> Search.search_data_for_create(user)

        search =
          search
          |> Changeset.change(number_results: search_data.data["total"])
          |> Repo.update!(force: true)

        pico_search = PicoSearch.get_pico_search(search)

        assigns = [
          pico_search: pico_search,
          search: search,
          data: search_data.data,
          bg_colour: get_client_colour(conn, :login_page_bg_colour),
          search_bar_colour: get_client_colour(conn, :search_bar_colour)
        ]
        render(conn, Bep.SearchView, "results.html", assigns)
    end
  end

  def edit(conn, %{"id" => pico_search_id, "note_id" => note_id, "search_id" => search_id}) do
    pico_search = Repo.get(PicoSearch, pico_search_id)
    note_search = Repo.get_by(NoteSearch, search_id: search_id)

    pico_outcomes =
      pico_search_id
      |> PicoOutcome.get_pico_outcomes()
      |> PicoOutcome.unique_outcomes()

    search = Repo.get(Search, search_id)
    changeset = PicoSearch.changeset(pico_search)

    assigns = [
      changeset: changeset,
      note_id: note_id,
      search: search,
      outcomes: pico_outcomes,
      note_search: note_search
    ]

    render(conn, "new.html", assigns)
  end

  # Helpers
  defp update_prob(params) do
    prob = params["probability"]
    prob = Regex.replace(~r/\D/, prob, "")
    Map.put(params, "probability", prob)
  end

  defp get_pico_outcomes(pico_search) do
    pico_search
    |> Map.keys()
    |> Enum.filter(&(&1 =~ "outcome_input"))
    |> Enum.reduce([], fn(key, acc) ->
      value = Map.get(pico_search, key)
      case value == "" do
        true -> acc
        false ->
          [_ , index] = String.split(key, "outcome_input")
          pico_outcome = %{
            o: Map.get(pico_search, "outcome_input#{index}"),
            o_index: Map.get(pico_search, "outcome_index#{index}"),
            benefit: Map.get(pico_search, "outcome_benefit#{index}")
          }
          [pico_outcome | acc]
      end
    end)
  end

  defp insert_or_update_pico(pico_search_params) do
    note_id = pico_search_params["note_id"]
    pico_search = Repo.get_by(PicoSearch, note_search_id: note_id)
    note_search = Repo.get(NoteSearch, note_id)

    case pico_search do
      nil ->
        %PicoSearch{}
        |> PicoSearch.changeset(pico_search_params)
        |> Changeset.put_assoc(:note_search, note_search)
        |> Repo.insert!()
      pico_search ->
        pico_search
        |> PicoSearch.changeset(pico_search_params)
        |> Repo.update!()
    end
  end
end

web/views/pico_search_view.ex
defmodule Bep.PicoSearchView do
  use Bep.Web, :view

  def render_outcomes(f, outcomes) do
    Enum.map(1..9, &render("outcome.html", [
      f: f,
      i: &1,
      outcome: Enum.at(outcomes, &1 - 1, %{o: ""})
    ]))
  end

  def outcome_index(str, i) do
    "outcome_#{str}_#{i}"
  end

  def create_atom(str, i) do
    String.to_atom("#{str}_#{i}")
  end
end

web/templates/pico_search/new.html.eex
<div class="w-80 center mb5 pt3 pt6-l">
  <%= form_for @changeset, pico_search_path(@conn, :create), [method: "post"], fn f -> %>
    <%= hidden_input f, :note_id, value: @note_id %>
    <%= hidden_input f, :search_id, value: @search.id %>
    <div class="flex">
      <img src="/images/progress2.svg" class="w-80">
    </div>
    <div class="">
      <h3 class="bb bep-b--maroon dib pb2 pr2 mt0">Structure the question</h3>
    </div>
    <p class="tl mt0 mb3 pa2 ba br2 bep-b--blue bep-gray"><%= @search.term %></p>
    <p class="f6 bep-red dib mt0">The above text is used in the search.</p>

    <div class="flex">
      <p class="b dib w-10">P</p>
      <%= text_input f, :p, placeholder: "Patient or population...", class: "mv2 ba br2 bep-b--blue w-90 bw1 pa2" %>
    </div>

    <div class="flex">
      <p class="b dib w-10">I</p>
      <%= text_input f, :i, placeholder: "Intervention or exposure...", class: "mv2 ba br2 bep-b--blue w-90 bw1 pa2" %>
    </div>
    <div class="flex">
      <p class="b dib w-10">C</p>
      <%= text_input f, :c, placeholder: "Comparator or control...", class: "mv2 ba br2 bep-b--blue w-90 bw1 pa2" %>
    </div>

    <p class="f7 bep-red dib mv1">Please put primary outcome first</p>
    <%= render_outcomes(f, @outcomes) %>

    <div class="tr">
      <button type="button" name="button" id="new-outcome" class="white br2 link pointer bep-bg-red f7 pv2 ph3">add another outcome</button>
    </div>

    <p>Current position</p>
    <div class="tc">
      <%= textarea f, :current_position, id: "current-position", placeholder: "What would you do if you only have the knowledge that you have now?", class: "w-90 ba br2 bep-b--gray pa2", rows: 5 %>
    </div>
    <p class="mb0">How likely do you think it is that it will be effective?</p>

    <div class="flex">
      <p class="dib f6 ml3">Prior probability: </p>
      <%= text_input f, :probability, id: "probability", placeholder: "50", class: "mv2 ba br2 bep-b--blue bw1 pv2 ph1 ml3 w4" %>
      <p class="b dib pl2">%</p>
    </div>

    <div class="tc">
      <%= submit "Search", name: "search_trip", value: "true", class: "white ph5 pv3 ba br2 link db center pointer bep-bg-blue mt2" %>
      <p>or</p>
      <%= submit "Save and continue later", class: "pointer bep-blue link db center bg-white bn mt2 bb" %>
    </div>
    <div class="tc">
      <a id="share-question" data-note="<%= @note_search.note %>" data-search="<%= @search.term %>" class="pointer bep-blue link db center bg-white bn mt2 bb" >Share your question with BestEvidence</a>
    </div>
  <% end %>
</div>

web/templates/pico_search/outcome.html.eex
<div id="<%= "outcome#{@i}" %>">
  <%= hidden_input @f, create_atom("outcome_index", @i), value: @i %>
  <div class="flex">
    <p class="b dib w-10">O</p>
    <%= text_input @f, create_atom("outcome_input", @i), placeholder: "Outcome of interest...", class: "mv2 ba br2 bep-b--blue w-90 bw1 pa2", value: @outcome.o %>
  </div>
    <p class="f6 mt0 ml4">What effect will this have on the patient?</p>
  <div class="">
    <%= radio_button @f, create_atom("outcome_benefit", @i), true, checked: true, id: outcome_index("benefit", @i), class: "ml4" %>
    <label for="<%= outcome_index("benefit", @i) %>" class="ml2">Benefit</label>
  </div>
  <div class="">
    <%= radio_button @f, create_atom("outcome_benefit", @i), false, checked: false, id: outcome_index("harm", @i), class: "ml4" %>
    <label for="<%= outcome_index("harm", @i) %>" class="ml2">Harm</label>
  </div>
</div>