web/router.ex
defmodule Bep.Router do
  use Bep.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Bep.Auth, repo: Bep.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/super-admin", Bep, as: :sa do
    pipe_through [:browser, :authenticate_super_admin]

    resources "/", SuperAdminController, only: [
      :index, :new, :create, :edit, :update
    ]
    get "/new-client-admin", SuperAdminController, :new_client_admin
    post "/create-client-admin", SuperAdminController, :create_client_admin
    get "/edit-client-admin", SuperAdminController, :edit_client_admin
    put "/update-client-admin/:id", SuperAdminController, :update_client_admin
    get "/list-users", MessagesController, :list_users
    post "/list-users", MessagesController, :view_user_messages
    get "/messages", MessagesController, :view_messages
    get "/message_sent", MessagesController, :message_sent
    resources "/messages", MessagesController, only: [:create, :new]
  end

  scope "/", Bep, as: :ca do
    pipe_through [:browser, :authenticate_ca]
    get "/list-users", MessagesController, :list_users
    post "/list-users", MessagesController, :view_user_messages
    get "/message_sent", MessagesController, :message_sent
    resources "/messages", MessagesController, only: [:create, :new]
  end

  scope "/", Bep do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create]
    resources "/consent", ConsentController, only: [:index]
    resources "/about", AboutController, only: [:index]
    resources "/password", PasswordController, only: [:index]
    post "/password/request", PasswordController, :request
    get "/password/reset", PasswordController, :reset
    post "/password/reset", PasswordController, :reset
  end

  scope "/", Bep do
    pipe_through [:browser, :authenticate_user]

    get "/paper-details", BearController, :paper_details
    get "/check-validity", BearController, :check_validity
    get "/calculate-results", BearController, :calculate_results
    get "/relevance", BearController, :relevance
    get "/bear-complete", BearController, :complete
    get "/create-pdf", BearController, :create_pdf
    post "/download-pdf", BearController, :download_pdf
    resources "/bears", BearController, only: [:index]
    resources "/bear-form", BearController, only: [:create]
    resources "/pico", PicoSearchController, [:new, :create, :edit]
    resources "/history", HistoryController, only: [:index]
    resources "/search", SearchController, only: [:index, :create]
    post "/search/category", SearchController, :filter
    resources "/settings", SettingsController, only: [:index]
    get "/password/change", PasswordController, :change_password
    post "/password/change", PasswordController, :change_password
    get "/messages", MessagesController, :view_messages
  end

  scope "/note", Bep do
    pipe_through [:browser, :authenticate_user]
    resources "/search", NoteSearchController
  end

  # Other scopes may use custom stacks.
  scope "/", Bep do
    pipe_through :api
    resources "/publication", PublicationController, only: [:create]
    get "/load", SearchController, :load
  end

  scope "/:client_slug", Bep, as: :client_slug do
    pipe_through [:browser, :authenticate_client]

    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create]
    resources "/consent", ConsentController, only: [:index]
    resources "/about", AboutController, only: [:index]
    resources "/password", PasswordController, only: [:index]
    post "/password/request", PasswordController, :request
    get "/password/reset", PasswordController, :reset
    post "/password/reset", PasswordController, :reset
  end
end

web/controllers/settings_controller.ex
defmodule Bep.SettingsController do
  use Bep.Web, :controller
  alias Bep.{OtherType, Type}

  def index(conn, _params) do
    user = conn.assigns.current_user
    types =
      Type.get_types()
      |> Enum.map(fn(t) ->
        %{
          id: t.id,
          type: t.type,
          checked: Enum.any?(user.types, fn(ut) -> t.id == ut.id end)
        }
      end)

    other_type = Repo.get_by(OtherType, user_id: user.id)

    other_value =
      case other_type do
        nil ->
          ""
        _ ->
          other_type.type
      end

    {other, types} = Type.separate_other(types)
    btn_colour = get_client_colour(conn, :btn_colour)
    assets = [
      types: types,
      other: other,
      changeset: user,
      btn_colour: btn_colour,
      other_value: other_value
    ]
    render(conn, "index.html", assets)
  end
end

web/views/settings_view.ex
defmodule Bep.SettingsView do
  use Bep.Web, :view
end

web/templates/settings/index.html.eex
<div class="vh-100">
  <section class="pt2 pt5-l pb4 mt4">
    <div class="w-80 w-50-ns center">
      <h4 class="f5 dib w-60 mt4">Settings</h4>
      <p class="f6 b mt0">User Type</p>
      <%= form_for @conn, user_path(@conn, :update, @current_user), [as: :types, method: :put], fn f -> %>
        <%= for type <- @types do %>
          <div class="db pb2 pl3 f6 tl">
            <%= checkbox f, :"#{type.id}", class: "pr2", checked: type.checked %>
            <%= label f, :"#{type.id}", type.type, class: "pointer" %>
          </div>
        <% end %>
        <div class="db pb2 pl3 f6 tl">
          <%= checkbox f, :"#{@other.id}", class: "pr2 other-checkbox", checked: @other.checked %>
          <%= label f, :"#{@other.id}", @other.type, class: "pointer" %>
          <%= text_input f, :other_type, placeholder: "e.g. Journalist", class: "other-type w5 ba br2 b--black-20 dn", value: @other_value %>
        </div>
        <%= submit "Update", class: "pointer bep-bg-red white ph2 f6 pv1 ba br2 link mb4", style: "background-color:#{@btn_colour}" %>
      <% end %>
      <%= link "Change Password", to: password_path(@conn, :change_password), class: "black f6" %>

      <%= if @client.slug == "default" do %>
        <%= link "Log out", to: user_path(@conn, :delete, @current_user),
        method: "delete", class: "black f6" %>
      <% else %>
        <%= link "Log out", to: client_slug_user_path(@conn, :delete, @client.slug, @current_user),
        method: "delete", class: "black f6" %>
      <% end %>
    </div>
  </section>
</div>