web/router.ex
defmodule Bep.Router do
  use Bep.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Bep.Auth, repo: Bep.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/super-admin", Bep, as: :sa do
    pipe_through [:browser, :authenticate_super_admin]

    resources "/", SuperAdminController, only: [
      :index, :new, :create, :edit, :update
    ]
    get "/new-client-admin", SuperAdminController, :new_client_admin
    post "/create-client-admin", SuperAdminController, :create_client_admin
    get "/edit-client-admin", SuperAdminController, :edit_client_admin
    put "/update-client-admin/:id", SuperAdminController, :update_client_admin
    get "/list-users", MessagesController, :list_users
    post "/list-users", MessagesController, :view_user_messages
    get "/messages", MessagesController, :view_messages
    get "/message_sent", MessagesController, :message_sent
    resources "/messages", MessagesController, only: [:create, :new]
  end

  scope "/", Bep, as: :ca do
    pipe_through [:browser, :authenticate_ca]
    get "/list-users", MessagesController, :list_users
    post "/list-users", MessagesController, :view_user_messages
    get "/message_sent", MessagesController, :message_sent
    resources "/messages", MessagesController, only: [:create, :new]
  end

  scope "/", Bep do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create]
    resources "/consent", ConsentController, only: [:index]
    resources "/about", AboutController, only: [:index]
    resources "/password", PasswordController, only: [:index]
    post "/password/request", PasswordController, :request
    get "/password/reset", PasswordController, :reset
    post "/password/reset", PasswordController, :reset
  end

  scope "/", Bep do
    pipe_through [:browser, :authenticate_user]

    get "/paper-details", BearController, :paper_details
    get "/check-validity", BearController, :check_validity
    get "/calculate-results", BearController, :calculate_results
    get "/relevance", BearController, :relevance
    get "/bear-complete", BearController, :complete
    get "/create-pdf", BearController, :create_pdf
    post "/download-pdf", BearController, :download_pdf
    resources "/bears", BearController, only: [:index]
    resources "/bear-form", BearController, only: [:create]
    resources "/pico", PicoSearchController, [:new, :create, :edit]
    resources "/history", HistoryController, only: [:index]
    resources "/search", SearchController, only: [:index, :create]
    post "/search/category", SearchController, :filter
    resources "/settings", SettingsController, only: [:index]
    get "/password/change", PasswordController, :change_password
    post "/password/change", PasswordController, :change_password
    get "/messages", MessagesController, :view_messages
  end

  scope "/note", Bep do
    pipe_through [:browser, :authenticate_user]
    resources "/search", NoteSearchController
  end

  # Other scopes may use custom stacks.
  scope "/", Bep do
    pipe_through :api
    resources "/publication", PublicationController, only: [:create]
    get "/load", SearchController, :load
  end

  scope "/:client_slug", Bep, as: :client_slug do
    pipe_through [:browser, :authenticate_client]

    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create]
    resources "/consent", ConsentController, only: [:index]
    resources "/about", AboutController, only: [:index]
    resources "/password", PasswordController, only: [:index]
    post "/password/request", PasswordController, :request
    get "/password/reset", PasswordController, :reset
    post "/password/reset", PasswordController, :reset
  end
end

web/controllers/about_controller.ex
defmodule Bep.AboutController do
  use Bep.Web, :controller

  def index(conn, _params) do
    bg_colour = get_client_colour(conn, :login_page_bg_colour)
    about_text = conn.assigns.client.about_text
    logo_url = conn.assigns.client.logo_url

    render(
      conn,
      "index.html",
      about_text: about_text,
      logo_url: logo_url,
      bg_colour: bg_colour
    )
  end
end

web/views/about_view.ex
defmodule Bep.AboutView do
  use Bep.Web, :view
end

web/templates/about/index.html.eex
<section style="background-color:<%= @bg_colour %>" class="tc white pt4 pt5-l pb3">
  <h1 class="f3 fw1 lh-copy pt3 pt4-l mv0"><%= be_for(@conn.assigns.client.name) %></h1>
</section>

<section class="pa3 w-80 w-30-ns center tc">
  <%= if @client.slug == "default" do %>
    <img src="/images/city-logo.jpg" alt="City University of London, Est 1894" class="w4">
    <p class="tl">
      Amanda Burls is the Director of <%= link "ThinkWell", to: "http://www.ithinkwell.org/", class: "bep-red" %> and Professor of Public Health at
      City, University of London. She conceived and designed the BestEvidence app.
    </p>
    <p class="tl">
      Jon Brassey is the Lead for Knowledge Mobilisation at Public Health Wales
      (NHS) and Director of Trip Database Ltd. <%= link "Trip database", to: "https://www.tripdatabase.com/", class: "bep-red" %> is the meta-search
      engine for clinical information used by BestEvidence.
    </p>
    <p class="tl">
      Jose Emparanza is the Head of the Department of Clinical Epidemiology Unit
      at the University Hospital Donostia, Spain and a founding member of the
      <%= link "International Society for Evidence-Based Health Care", to: "http://www.isehc.net/", class: "bep-red" %>. He explored the
      utility and acceptability of BestEvidence for promoting evidence-based
      practice with clinicians and established that there is a need and demand
      for this tool.
    </p>
    <p class="tl pb4">
      <%= link "City, University of London", to: "https://www.city.ac.uk/", class: "bep-red" %> is a world-leading centre for healthcare
      education and applied healthcare research. City funded the development of
      BestEvidence in order to facilitate the use of research evidence to inform
      and improve learning, practice and policy and thereby improve patient outcomes.
    </p>
  <% else %>
    <div class="about-text-raw">
      <img src="<%= @logo_url %>" class="w4">
      <%= raw @about_text %>
    </div>
  <% end %>

  <%= slug_link_helper(@conn, "Return to Home", &client_slug_page_path/3, &page_path/2, [route: :index, class: "bep-red underline f6 f5-ns"]) %>
</section>